name: PlaceholderAPI
main: "me.clip.placeholderapi.PlaceholderAPIPlugin"

version: ${version}
author: HelpChat

api-version: "1.13"
description: "An awesome placeholder provider!"

commands:
  placeholderapi:
    description: "PlaceholderAPI Command"
    aliases: ["papi"]

permissions:
  placeholderapi.*:
    description: "Ability to use all PAPI commands"
    children:
      placeholderapi.admin: true
      placeholderapi.ecloud.*: true
  placeholderapi.admin:
    description: "Ability to use all PAPI commands"
    children:
      placeholderapi.help: true
      placeholderapi.info: true
      placeholderapi.list: true
      placeholderapi.parse: true
      placeholderapi.reload: true
      placeholderapi.version: true
      placeholderapi.register: true
      placeholderapi.unregister: true
      placeholderapi.updatenotify: true
  placeholderapi.ecloud.*:
    description: "Ability to use all PAPI ecloud commands"
    children:
      placeholderapi.ecloud: true
      placeholderapi.ecloud.info: true
      placeholderapi.ecloud.list: true
      placeholderapi.ecloud.clear: true
      placeholderapi.ecloud.toggle: true
      placeholderapi.ecloud.status: true
      placeholderapi.ecloud.update: true
      placeholderapi.ecloud.refresh: true
      placeholderapi.ecloud.download: true
      placeholderapi.ecloud.placeholders: true
  placeholderapi.help:
    default: "op"
    description: "Allows you to view the list of PAPI commands"
  placeholderapi.info:
    default: "op"
    description: "Allows you to view expansion information"
  placeholderapi.list:
    default: "op"
    description: "Allows you to list active expansions"
  placeholderapi.ecloud:
    default: "op"
    description: "Allows you to access PAPI eCloud"
  placeholderapi.parse:
    default: "op"
    description: "Allows you to parse placeholders"
  placeholderapi.reload:
    default: "op"
    description: "Allows you to reload PAPI and its configuration"
  placeholderapi.version:
    default: "op"
    description: "Allows you to view the version of PAPI installed"
  placeholderapi.register:
    default: "op"
    description: "Allows you to register expansions"
  placeholderapi.unregister:
    default: "op"
    description: "Allows you to unregister expansions"
  placeholderapi.updatenotify:
    default: "op"
    description: "Notifies you when there is a PAPI update"
  placeholderapi.ecloud.info:
    default: "op"
    description: "Allows you to view cloud expansion information"
  placeholderapi.ecloud.list:
    default: "op"
    description: "Allows you to list eCloud expansions"
  placeholderapi.ecloud.clear:
    default: "op"
    description: "Allows you to clear the local eCloud expansion cache"
  placeholderapi.ecloud.toggle:
    default: "op"
    description: "Allows you to toggle/enable/disable the eCloud manager"
  placeholderapi.ecloud.status:
    default: "op"
    description: "Allows you to view the status of eCloud expansions"
  placeholderapi.ecloud.update:
    default: "op"
    description: "Allows you to update registered eCloud expansions"
  placeholderapi.ecloud.refresh:
    default: "op"
    description: "Allows you to refresh the local eCloud expansion cache"
  placeholderapi.ecloud.download:
    default: "op"
    description: "Allows you to download an expansion from the eCloud"
  placeholderapi.ecloud.placeholders:
    default: "op"
    description: "Allows you to view the placeholders of a eCloud expansion"